name: E2E
on:
  pull_request:
jobs:
  e2e-test:
    runs-on: ubuntu-22.04
    name: E2E Test
    timeout-minutes: 40
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Clusters
        uses: helm/kind-action@v1.8.0
        with:
          version: v0.20.0
          install_only: true
      - name: Set Up Clusters
        run: |
          hack/e2e-test/build-clusters.sh
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.1
      - name: Init kurator cluster
        run: |
          hack/e2e-test/install-kurator.sh
      - name: fleet-clusters e2e test
        run: |
          hack/e2e-test/run-e2e.sh
